#!/usr/bin/env bash

#
# blackbox_postdeploy -- Decrypt all blackbox files.
#
if [[ "$1" == "" ]]; then
  blackbox decrypt --all --overwrite
else
  blackbox decrypt --all --overwrite --group "$1" "
fi
