name: build-and-test

ono: [pull_request, push] # TODO remove "push". Add it just for debugging

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repo
         users: actions/checkout@v2
         with:
           fetch-depth: 0
       - name: Build Docker image
         users: docker/build-push-action@v1
         with:
           push: false
