on:
  release:
    types: [published]

name: release
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Build binaries
      working-directory: cmd/blackbox
      run: go build

    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ./cmd/blackbox/blackbox
        asset_name: blackbox
        asset_content_type: application/octet-stream

